
tests: 
	cd ./basic ; make redo ; cd ../
	cd ./basicFLY ; make redo ; cd ../
	cd ./explicitFLY ; make redo ; cd ../
	cd ./fileFLY  ; make redo ; cd ../
	cd ./largeFileSlidingFLY  ; make redo ; cd ../
	cd ./slidingFLY  ; make redo ; cd ../
	cd ./serializedEncoder ; make redo ; cd ../

clean:
	cd ./basic ; make clean ; cd ../
	cd ./basicFLY ; make clean ; cd ../
	cd ./explicitFLY ; make clean ; cd ../
	cd ./fileFLY  ; make clean ; cd ../
	cd ./largeFileSlidingFLY  ; make clean ; cd ../
	cd ./slidingFLY  ; make clean ; cd ../
	cd ./serializedEncoder ; make clean ; cd ../
